# Generated by Django 4.2.8 on 2024-01-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_author_comments_remove_feeds_auther_delete_searches_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
