# Generated by Django 4.2.8 on 2024-01-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_comments_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
