# Generated by Django 3.2.12 on 2024-01-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_comments_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='top_level_comment_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.comments'),
        ),
    ]
