# Generated by Django 3.2.12 on 2024-01-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_comments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='top_level_comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
